.\" Process this file with
.\" groff -man -Tascii ailurus.1
.\"
.TH AILURUS 1 "AUGUST 2012" Linux "User Manuals"
.SH NAME
Ailurus \- recording installed software, recovering system later
.SH SYNOPSIS
.B ailurus [
.I OPTIONS
.B ]
.SH DESCRIPTION
.B Ailurus
is a tool for recording installed software and recovering system later.

Copyright 2007-2012. Licensed under GPL, version 2 or higher version.
